//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sale
    {
        public int SaleId { get; set; }
        public string ContractId { get; set; }
        public Nullable<int> ColonyId { get; set; }
        public Nullable<int> PlotId { get; set; }
        public Nullable<int> SaleStatus { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> NoOfMonth { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<int> DateOfPay { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
