//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SaleInstall
    {
        public int ISaleId { get; set; }
        public string ContractNo { get; set; }
        public Nullable<int> ClienId { get; set; }
        public Nullable<int> ColonyId { get; set; }
        public Nullable<int> PlotId { get; set; }
        public string SaleStatus { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> TotalInstall { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public Nullable<int> DatOfPay { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
