//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Colony
    {
        public int ColonyId { get; set; }
        public string ColonyName { get; set; }
        public string Location { get; set; }
        public string Area { get; set; }
        public string OwnerName { get; set; }
        public string FName { get; set; }
        public string Cnic { get; set; }
        public string Address { get; set; }
    }
}
