//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealStateManagment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Plot
    {
        public int PlotId { get; set; }
        public Nullable<int> PlotNo { get; set; }
        public string PlotArea { get; set; }
        public Nullable<decimal> PlotAmount { get; set; }
        public string Status { get; set; }
        public Nullable<int> ColonyId { get; set; }
        public string ColonyName { get; set; }
    }
}
